development:
  adapter: mysql2
  database: contactlist_development
  host: localhost
  username: root
  password:

production:
  adapter: mysql2
  database: contactlist_production
  host: localhost
  username: root
  password: